---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: appdynamics-common
data:
  APPD_DIR: "/appdynamics"
  APPD_ES_HOST: "10.97.11.95"
  APPD_ES_PORT: "9080"
  APPD_ES_SSL: "false"
  APPD_EVENT_ACCOUNT_NAME: "customer1_3cd654eb-ecbd-4ff1-b879-b1ad53a2f2ab"
  APPDYNAMICS_AGENT_APPLICATION_NAME: "Koala_Solutions"
  APPDYNAMICS_CONTROLLER_HOST_NAME: "10.97.11.95"
  APPDYNAMICS_CONTROLLER_PORT: "8090"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
  #APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
  #APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "Koala-Java-Pod"
  APPD_JAVAAGENT: "-javaagent:/opt/appdynamics-agents/java/javaagent.jar"
  APPDYNAMICS_NETVIZ_AGENT_PORT: "3892"
  JAVA_OPTS: "-javaagent:/opt/appdynamics-agents/java/javaagent.jar -Dappdynamics.agent.nodeName=$(hostname)"