---
apiVersion: v1
kind: Secret
metadata:
  name: appdynamics-secrets
type: Opaque
data:
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "YmNjMzU0YjMtM2FhOS00ZmFiLWIxM2UtOWQ0YmQzZWY3MTgxCg=="
  APPDYNAMICS_AGENT_ACCOUNT_NAME: "Y3VzdG9tZXIxX2E5NzFmOWIwLWJlM2MtNDM0Zi1hYmIzLWNhYTA4MjlhMzc0NWJhc2U2NAo="