apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-restful-web-services
  name: java-restful-web-services
spec:
  replicas: 5
  selector:
    matchLabels:
      app: java-restful-web-services
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-restful-web-services
    spec:
      containers:
        - image: diegokoala/java-restful-web-services
          name: java-restful-web-services
          resources: {}
status: {}
