---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  accesskey: "YmNjMzU0YjMtM2FhOS00ZmFiLWIxM2UtOWQ0YmQzZWY3MTgxCg=="
  accountname: "Y3VzdG9tZXIxX2E5NzFmOWIwLWJlM2MtNDM0Zi1hYmIzLWNhYTA4MjlhMzc0NWJhc2U2NAo="