---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  accesskey: "YzVjN2U0NTgtYmQ1ZC00MDQ2LTg1YmEtMDk5ODY4ZjExODY5Cg=="
  accountname: "Y3VzdG9tZXIxXzNjZDY1NGViLWVjYmQtNGZmMS1iODc5LWIxYWQ1M2EyZjJhYgo="